mithril:
  build: .
  volumes:
    - .:/usr/src/app
    - /etc/localtime:/etc/localtime:ro
    - /usr/src/app/node_modules
  ports:
    - "3030:3030"
    - "8080:8080"
  environment:
    - EXPRESS_PORT=3030
    - DEV_SERVER_PORT=8080
    - DEV_SERVER_LISTEN=0.0.0.0
